# Generated by Django 5.2 on 2025-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='member_one',
            field=models.CharField(default='DefaultName', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='member_two',
            field=models.CharField(default='DefaultName', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='DefaultName', max_length=20),
            preserve_default=False,
        ),
    ]
