# Generated by Django 5.2 on 2025-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_note_content_remove_note_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='member_one',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='member_two',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
