# Generated by Django 5.2 on 2025-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tournamentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgroup',
            name='author',
        ),
        migrations.AlterField(
            model_name='tournamentgroup',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
