# Generated by Django 5.2 on 2025-04-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tournamentgroup_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='author',
        ),
    ]
