# Generated by Django 5.2 on 2025-04-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_team_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.PositiveIntegerField(blank=True, null=True)),
                ('score_team2', models.PositiveIntegerField(blank=True, null=True)),
                ('played', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.tournamentgroup')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='api.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='api.team')),
            ],
            options={
                'unique_together': {('group', 'team1', 'team2')},
            },
        ),
    ]
