# Generated by Django 5.2 on 2025-04-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.PositiveIntegerField(blank=True, null=True)),
                ('score_team2', models.PositiveIntegerField(blank=True, null=True)),
                ('played', models.BooleanField(default=False)),
                ('round', models.CharField(choices=[('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=3)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ko_games_as_team1', to='api.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ko_games_as_team2', to='api.team')),
            ],
        ),
    ]
