# Generated by Django 5.2 on 2025-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_knockoutgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knockoutgame',
            name='round',
            field=models.CharField(choices=[('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Grand Final')], max_length=3),
        ),
    ]
